FROM golang:1.18 AS builder
WORKDIR /project
ENV CGO_ENABLED=0
ENV GOOS=linux
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o seek-checkout -a

FROM scratch AS final
EXPOSE 8080
WORKDIR /app
# ENV GIN_MODE=release
COPY --from=builder /project/seek-checkout .
ENTRYPOINT ["/app/seek-checkout"]